"""Add setup token fields to User

Revision ID: 3aba1a01eb0c
Revises: 461e6b724078
Create Date: 2026-01-21 14:22:25.185022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aba1a01eb0c'
down_revision = '461e6b724078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_token_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('setup_token_created_at')

    # ### end Alembic commands ###
